version: "3"

services:
  # dev:
  #   image: node:12
  #   build: .
  #   volumes:
  #     - .:/home/node/app
  #   command: npm run dev
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "3000:3000"
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_URL: postgres://postgres:postgres@postgres:5432/postgres
  #     NODE_ENV: development
  redis:
    image: "redis:alpine"
    expose:
      - '6379'
    ports:
      - "6379:6379"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dashboard
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_DATABASE: dashboard
    restart: always
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - ./resources/database/setup.sql:/docker-entrypoint-initdb.d/init.sql
